add and setup prettier + update ci, dependabot and githooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -16,5 +16,13 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+echo "Checking frontend formatting..."
+npm run prettier:check
+
+if [ $? -ne 0 ]; then
+    echo "Prettier check failed. Run 'npm run prettier:format' to fix. Commit aborted."
+    exit 1
+fi
+
 echo "All checks passed. Proceeding with commit."
 exit 0
