Add ci (#1)
* fix linting errors and format code

* move tests to ci, check linting and formatting on commit

* commit migration files

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,14 +1,20 @@
 #!/bin/sh
 
-echo "Running tests before commit..."
+echo "Running linter..."
+ruff check .
 
-python manage.py test
-
-if [ $? -ne 0]; then
-    echo "Tests failed. Commit aborted"
+if [ $? -ne 0 ]; then
+    echo "Linting failed. Commit aborted."
     exit 1
-
 fi
 
-echo "All tests passed. Proceeding with commit."
+echo "Checking formatting..."
+ruff format --check .
+
+if [ $? -ne 0 ]; then
+    echo "Formatting check failed. Run 'ruff format .' to fix. Commit aborted."
+    exit 1
+fi
+
+echo "All checks passed. Proceeding with commit."
 exit 0
